### PR TITLE
I just fixed sum typos because I got triggered

### PR DESCRIPTION
**Pull request by DevilJamJar**
I just fixed sum typos because I got triggered

### CODE REVIEW

**Comment by blitzwolfz** [comment]
ok

**Comment by JonathanTheZero** [comment]
Lol this is blitz' code... fucking native speakers

**Review by JonathanTheZero — APPROVED** [review]
Looks good. Obviously you didn't change functionality but it's a nice improvement. Shall I merge this or you want to search for more?

**Comment by DevilJamJar** [comment]
I will search for more I think, I’ll tell you when I’m done or high and can’t feel my fingers to type much longer

**Comment by DevilJamJar** [comment]
Yeah can't really find anymore, feel free to merge

**Review by JonathanTheZero — APPROVED** [review]
Dis change good, will merge now

**Pull request merged**
