### PR TITLE
Contracts

### PR DESCRIPTION
**Pull request by blitzwolfz**
started shit

for Freaglii: added stuff

### CODE REVIEW

**Comment by blitzwolfz** [comment]
Ok I think you could use the contract system for wars. When they lose, the winner creates a contract that gets placed upon the loser to pay up. Just some thoughts

**Comment by blitzwolfz** [comment]
Ok now that I figured out how to DM users, this will allow users to be told when they get a proposal, and soon other notifications. By allowing DMs we could potentially have contracts with anyone that plays Utopia

**Comment by blitzwolfz** [comment]
Finished main components of the system didn't finish everything for update msg system

**Comment by blitzwolfz** [comment]
Finished update msg system. bot can now send DMs and fetch update msg from db. This will be later used to as a for automation and allow users not in the main server to find out about new updates. In addition this can be used to DM users one on one if need be if there are questions or such. In Freaglii terms: Added stuff

**Comment by blitzwolfz** [comment]
Finally finished update msg system

In Freaglii terms: added stuff
In Polish terms: dodane rzeczy

**Comment by JonathanTheZero** [comment]
yo, why are you writing so many comments suddenly??

**Comment by blitzwolfz** [comment]
idfk man

**Comment by blitzwolfz** [comment]
Ok it's done for now, but I have a few edge cases to work on for the proposal system. After this, I still have to work on all the other functionality for contracts

**Comment by blitzwolfz** [comment]
fixed errors for displaying contacts

**Comment by blitzwolfz** [comment]
finished accepting contracts

Freaglii: added stuff
Astilimos: dodano rzeczy

**Comment by blitzwolfz** [comment]
so I umm deleted dist thinking there was a bug in there, so I just generated a new dist folder ya.

Freaglii & Astilimos: ADDED A TON OF SHIT


on a further note, Contracts are done, I have a few things to test and i got payouts and everything working

**Comment by blitzwolfz** [comment]
Also I want to revamp loans

**Comment by blitzwolfz** [comment]
Okay leave the loan revamp alone, I have few plans for it, but otherwise everything is a go

**Comment by blitzwolfz** [comment]
changed say command

**Pull request merged**
