### PR TITLE
Added modmail support

### PR DESCRIPTION
**Pull request by blitzwolfz**
This will allow users to mail us with issues and whatnot

### CODE REVIEW

**Comment by blitzwolfz** [comment]
stuff

**Comment by blitzwolfz** [comment]
Crtl + C and Crtl+ V ;)

**Comment by JonathanTheZero** [comment]
or just write good code

**Comment by blitzwolfz** [comment]
Smh, mistakes are made in the heat of passion jumbo

**Comment by JonathanTheZero** [comment]
*jimbo

**Comment by blitzwolfz** [comment]
Smh

**Pull request closed without merging**
